//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class codeFirstEntities : DbContext
    {
        public codeFirstEntities()
            : base("name=codeFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<JD_Commodity_001> JD_Commodity_001 { get; set; }
        public DbSet<JD_Commodity_002> JD_Commodity_002 { get; set; }
        public DbSet<JD_Commodity_003> JD_Commodity_003 { get; set; }
        public DbSet<JD_Commodity_004> JD_Commodity_004 { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserMenuMapping> UserMenuMapping { get; set; }
    }
}
